"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2025-11-01 23:48:43.514482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('authority_level', sa.String(length=20), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('processing_days', sa.Integer(), nullable=True),
    sa.Column('supports_physical', sa.Boolean(), nullable=True),
    sa.Column('supports_digital', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('issue_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('psgc_code', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('flag_url', sa.String(length=255), nullable=True),
    sa.Column('trademark_image_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('land_area', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('psgc_code'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('barangays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('psgc_code', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipality_id', 'name', name='uq_municipality_barangay_name'),
    sa.UniqueConstraint('psgc_code')
    )
    op.create_table('benefit_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('program_type', sa.String(length=50), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('eligibility_criteria', sa.JSON(), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('application_start', sa.DateTime(), nullable=True),
    sa.Column('application_end', sa.DateTime(), nullable=True),
    sa.Column('benefit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('benefit_description', sa.Text(), nullable=True),
    sa.Column('max_beneficiaries', sa.Integer(), nullable=True),
    sa.Column('current_beneficiaries', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_accepting_applications', sa.Boolean(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('suffix', sa.String(length=10), nullable=True),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('barangay_id', sa.Integer(), nullable=True),
    sa.Column('street_address', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('admin_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('valid_id_front', sa.String(length=255), nullable=True),
    sa.Column('valid_id_back', sa.String(length=255), nullable=True),
    sa.Column('proof_of_residency', sa.String(length=255), nullable=True),
    sa.Column('selfie_with_id', sa.String(length=255), nullable=True),
    sa.Column('admin_municipality_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('admin_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_municipality', ['municipality_id'], unique=False)
        batch_op.create_index('idx_user_role', ['role'], unique=False)
        batch_op.create_index('idx_user_username', ['username'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index('idx_announcement_active', ['is_active'], unique=False)
        batch_op.create_index('idx_announcement_created', ['created_at'], unique=False)
        batch_op.create_index('idx_announcement_municipality', ['municipality_id'], unique=False)
        batch_op.create_index('idx_announcement_priority', ['priority'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_audit_muni', ['municipality_id'], unique=False)

    op.create_table('benefit_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('application_data', sa.JSON(), nullable=True),
    sa.Column('supporting_documents', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('disbursement_status', sa.String(length=20), nullable=True),
    sa.Column('disbursement_date', sa.DateTime(), nullable=True),
    sa.Column('disbursement_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['benefit_programs.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number')
    )
    with op.batch_alter_table('benefit_applications', schema=None) as batch_op:
        batch_op.create_index('idx_benefit_app_number', ['application_number'], unique=False)
        batch_op.create_index('idx_benefit_app_program', ['program_id'], unique=False)
        batch_op.create_index('idx_benefit_app_status', ['status'], unique=False)
        batch_op.create_index('idx_benefit_app_user', ['user_id'], unique=False)

    op.create_table('document_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('barangay_id', sa.Integer(), nullable=True),
    sa.Column('delivery_method', sa.String(length=20), nullable=False),
    sa.Column('delivery_address', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('supporting_documents', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('qr_data', sa.JSON(), nullable=True),
    sa.Column('document_file', sa.String(length=255), nullable=True),
    sa.Column('resident_input', sa.JSON(), nullable=True),
    sa.Column('admin_edited_content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number')
    )
    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        batch_op.create_index('idx_doc_request_municipality', ['municipality_id'], unique=False)
        batch_op.create_index('idx_doc_request_number', ['request_number'], unique=False)
        batch_op.create_index('idx_doc_request_status', ['status'], unique=False)
        batch_op.create_index('idx_doc_request_user', ['user_id'], unique=False)

    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('barangay_id', sa.Integer(), nullable=True),
    sa.Column('specific_location', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('admin_response_by', sa.Integer(), nullable=True),
    sa.Column('admin_response_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('status_updated_by', sa.Integer(), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('upvote_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_response_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['issue_categories.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['status_updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_number')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index('idx_issue_category', ['category_id'], unique=False)
        batch_op.create_index('idx_issue_municipality', ['municipality_id'], unique=False)
        batch_op.create_index('idx_issue_number', ['issue_number'], unique=False)
        batch_op.create_index('idx_issue_priority', ['priority'], unique=False)
        batch_op.create_index('idx_issue_status', ['status'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lend_duration_days', sa.Integer(), nullable=True),
    sa.Column('security_deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('barangay_id', sa.Integer(), nullable=True),
    sa.Column('pickup_location', sa.String(length=200), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('idx_item_category', ['category'], unique=False)
        batch_op.create_index('idx_item_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_item_municipality', ['municipality_id'], unique=False)
        batch_op.create_index('idx_item_status', ['status'], unique=False)
        batch_op.create_index('idx_item_transaction_type', ['transaction_type'], unique=False)

    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index('idx_token_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_token_jti', ['jti'], unique=False)
        batch_op.create_index('idx_token_user', ['user_id'], unique=False)

    op.create_table('transfer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_municipality_id', sa.Integer(), nullable=False),
    sa.Column('to_municipality_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['to_municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('status_change', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_deleted_by_sender', sa.Boolean(), nullable=True),
    sa.Column('is_deleted_by_receiver', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_message_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_message_item', ['item_id'], unique=False)
        batch_op.create_index('idx_message_receiver', ['receiver_id'], unique=False)
        batch_op.create_index('idx_message_sender', ['sender_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('borrow_start_date', sa.DateTime(), nullable=True),
    sa.Column('borrow_end_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('pickup_at', sa.DateTime(), nullable=True),
    sa.Column('buyer_notes', sa.Text(), nullable=True),
    sa.Column('seller_notes', sa.Text(), nullable=True),
    sa.Column('pickup_location', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transaction_buyer', ['buyer_id'], unique=False)
        batch_op.create_index('idx_transaction_seller', ['seller_id'], unique=False)
        batch_op.create_index('idx_transaction_status', ['status'], unique=False)

    op.create_table('transaction_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_created', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_tx', ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_tx')
        batch_op.drop_index('idx_audit_created')

    op.drop_table('transaction_audit_logs')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_transaction_status')
        batch_op.drop_index('idx_transaction_seller')
        batch_op.drop_index('idx_transaction_buyer')

    op.drop_table('transactions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_message_sender')
        batch_op.drop_index('idx_message_receiver')
        batch_op.drop_index('idx_message_item')
        batch_op.drop_index('idx_message_created_at')

    op.drop_table('messages')
    op.drop_table('issue_updates')
    op.drop_table('transfer_requests')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index('idx_token_user')
        batch_op.drop_index('idx_token_jti')
        batch_op.drop_index('idx_token_expires')

    op.drop_table('token_blacklist')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('idx_item_transaction_type')
        batch_op.drop_index('idx_item_status')
        batch_op.drop_index('idx_item_municipality')
        batch_op.drop_index('idx_item_created_at')
        batch_op.drop_index('idx_item_category')

    op.drop_table('items')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index('idx_issue_status')
        batch_op.drop_index('idx_issue_priority')
        batch_op.drop_index('idx_issue_number')
        batch_op.drop_index('idx_issue_municipality')
        batch_op.drop_index('idx_issue_category')

    op.drop_table('issues')
    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_doc_request_user')
        batch_op.drop_index('idx_doc_request_status')
        batch_op.drop_index('idx_doc_request_number')
        batch_op.drop_index('idx_doc_request_municipality')

    op.drop_table('document_requests')
    with op.batch_alter_table('benefit_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_benefit_app_user')
        batch_op.drop_index('idx_benefit_app_status')
        batch_op.drop_index('idx_benefit_app_program')
        batch_op.drop_index('idx_benefit_app_number')

    op.drop_table('benefit_applications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_muni')
        batch_op.drop_index('idx_audit_entity')
        batch_op.drop_index('idx_audit_created_at')

    op.drop_table('audit_logs')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index('idx_announcement_priority')
        batch_op.drop_index('idx_announcement_municipality')
        batch_op.drop_index('idx_announcement_created')
        batch_op.drop_index('idx_announcement_active')

    op.drop_table('announcements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_role')
        batch_op.drop_index('idx_user_municipality')
        batch_op.drop_index('idx_user_email')

    op.drop_table('users')
    op.drop_table('benefit_programs')
    op.drop_table('barangays')
    op.drop_table('municipalities')
    op.drop_table('issue_categories')
    op.drop_table('document_types')
    # ### end Alembic commands ###
