"""add transaction audit log

Revision ID: 2bc95540bb7b
Revises: 0001_initial
Create Date: 2025-10-29 15:18:42.587523

"""
from alembic import op
import sqlalchemy as sa


def _table_exists(bind, table_name: str) -> bool:
    inspector = sa.inspect(bind)
    return table_name in inspector.get_table_names()


def _index_exists(bind, table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(bind)
    return any(idx.get('name') == index_name for idx in inspector.get_indexes(table_name))


def _column_is_json(bind, table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(bind)
    for column in inspector.get_columns(table_name):
        if column['name'] == column_name:
            return column['type'].__class__.__name__.lower() == 'json'
    return False


# revision identifiers, used by Alembic.
revision = '2bc95540bb7b'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()

    if not _table_exists(bind, 'transaction_audit_logs'):
        op.create_table(
            'transaction_audit_logs',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('transaction_id', sa.Integer(), nullable=False),
            sa.Column('actor_id', sa.Integer(), nullable=True),
            sa.Column('actor_role', sa.String(length=20), nullable=True),
            sa.Column('action', sa.String(length=50), nullable=False),
            sa.Column('from_status', sa.String(length=20), nullable=True),
            sa.Column('to_status', sa.String(length=20), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('ip_address', sa.String(length=64), nullable=True),
            sa.Column('user_agent', sa.String(length=255), nullable=True),
            sa.Column('metadata', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['actor_id'], ['users.id']),
            sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id']),
            sa.PrimaryKeyConstraint('id')
        )

    if not _index_exists(bind, 'transaction_audit_logs', 'idx_audit_created'):
        with op.batch_alter_table('transaction_audit_logs', schema=None) as batch_op:
            batch_op.create_index('idx_audit_created', ['created_at'], unique=False)

    if not _index_exists(bind, 'transaction_audit_logs', 'idx_audit_tx'):
        with op.batch_alter_table('transaction_audit_logs', schema=None) as batch_op:
            batch_op.create_index('idx_audit_tx', ['transaction_id'], unique=False)

    if not _column_is_json(bind, 'announcements', 'images'):
        with op.batch_alter_table('announcements', schema=None) as batch_op:
            batch_op.alter_column(
                'images',
                existing_type=sa.TEXT(),
                type_=sa.JSON(),
                existing_nullable=True
            )

    if not _column_is_json(bind, 'document_requests', 'resident_input'):
        with op.batch_alter_table('document_requests', schema=None) as batch_op:
            batch_op.alter_column(
                'resident_input',
                existing_type=sa.TEXT(),
                type_=sa.JSON(),
                existing_nullable=True
            )

    if not _column_is_json(bind, 'document_requests', 'admin_edited_content'):
        with op.batch_alter_table('document_requests', schema=None) as batch_op:
            batch_op.alter_column(
                'admin_edited_content',
                existing_type=sa.TEXT(),
                type_=sa.JSON(),
                existing_nullable=True
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        batch_op.alter_column('admin_edited_content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('resident_input',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('transaction_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_tx')
        batch_op.drop_index('idx_audit_created')

    op.drop_table('transaction_audit_logs')
    # ### end Alembic commands ###
