"""add external_url to announcements

Revision ID: 7e00b3f22e71
Revises: 20251029_add_audit_logs
Create Date: 2025-10-29 21:35:56.886621

"""
from alembic import op
import sqlalchemy as sa


def _has_column(bind, table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(bind)
    return any(column['name'] == column_name for column in inspector.get_columns(table_name))


# revision identifiers, used by Alembic.
revision = '7e00b3f22e71'
down_revision = '20251029_add_audit_logs'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    if not _has_column(bind, 'announcements', 'external_url'):
        with op.batch_alter_table('announcements', schema=None) as batch_op:
            batch_op.add_column(sa.Column('external_url', sa.String(length=500), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('external_url')

    # ### end Alembic commands ###
